DELETE  {{host_https}}/{{api_v1_route}}/users/f0066a52-272a-4718-b235-2c0e125dbb5f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmMDA2NmE1Mi0yNzJhLTQ3MTgtYjIzNS0yYzBlMTI1ZGJiNWYiLCJqdGkiOiJmMDU0ZWZmOC0yYmM2LTQ3MjUtODBjZS00ZmNiZTQzYjg3OTQiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwiZXhwIjoxNjgyNTI4NzI5LCJpc3MiOiJUYWJsZVRvcCBGcmllbmQiLCJhdWQiOiJUYWJsZVRvcCBGcmllbmQifQ.B70T2J6g7dTryIFgoOnodUhjcpPbbNCmldc9YfMWZCw