DELETE  {{host_https}}/{{api_v1_route}}/users/652f2f44-8b58-4a99-9fcd-1b98597b18c0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTJmMmY0NC04YjU4LTRhOTktOWZjZC0xYjk4NTk3YjE4YzAiLCJqdGkiOiI3N2U5YWY0Ny1iNDQ3LTQ5MTItOTllYy02YTRiOWM4MDVkZTQiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwiZXhwIjoxNjgyNTY0OTM2LCJpc3MiOiJUYWJsZVRvcCBGcmllbmQiLCJhdWQiOiJUYWJsZVRvcCBGcmllbmQifQ.DVuwkMXV_yB9mmws_avOYBt2LDP2avsHGqUC-MzDS6Q