GET {{host_https}}/{{api_v1_route}}/characters/list/b5309738-89e9-4af6-ac66-73c67577d621
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNTMwOTczOC04OWU5LTRhZjYtYWM2Ni03M2M2NzU3N2Q2MjEiLCJqdGkiOiIzNWYwZDJkNS00ZTRjLTQwZDItODczNS03MGFkN2Q2MDIwYTUiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwiZXhwIjoxNjgyMzQzMTk3LCJpc3MiOiJUYWJsZVRvcCBGcmllbmQiLCJhdWQiOiJUYWJsZVRvcCBGcmllbmQifQ.cXrLNXBBvx-HZfDQWgVcnzZnW8EagLuuGIuqEX0DaOs
