GET {{host_https}}/{{api_v1_route}}/characters/b425747e-e467-4259-9f6a-c0c1b93874fb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNTMwOTczOC04OWU5LTRhZjYtYWM2Ni03M2M2NzU3N2Q2MjEiLCJqdGkiOiJkOTUzYzI2Ny01ZTllLTRhNTAtYmJiYy1kMTIyYmYwZmQwNWEiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwiZXhwIjoxNjgyMzQ2Njg3LCJpc3MiOiJUYWJsZVRvcCBGcmllbmQiLCJhdWQiOiJUYWJsZVRvcCBGcmllbmQifQ.Rbr-m8A8mmw6oexI8b8d87dBcAeUtnBfZIjXbitU9Fk