version: '3.4'

services:
  tableTopFriend.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "\\@root123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      HOMEBREW_NO_ENV_FILTERING: "1"
    ports:
      - "1433:1433"