version: '3.4'

services:
  dddtabletopfriend.api:
    image: ${DOCKER_REGISTRY-}dddtabletopfriendapi
    build:
      context: .
      dockerfile: DDDTableTopFriend.Api/Dockerfile
    depends_on:
      - tableTopFriend.db
      - tableTopFriend.caching
    ports:
      - "5000:80"
      - "44388:443"

  tableTopFriend.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "\\@root123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      HOMEBREW_NO_ENV_FILTERING: "1"
    ports:
      - "1433:1433"

  tableTopFriend.caching:
    image: redis
    ports:
      - 6379:6379