POST {{host_https}}/{{api_v1_route}}/auth/register
Content-Type: application/json

{
    "firstName":"John",
    "lastName":"Doe",
    "email":"johndoe@anonymous.com",
    "password":"12345678",
    "role": 0
}