POST {{host_https}}/{{api_v1_route}}/auth/register
Content-Type: application/json

{
    "firstName":"Atos",
    "lastName":"Pedro",
    "email":"emailteste@gmail.com",
    "password":"123",
    "role": 0
}