POST {{host_https}}/{{api_v1_route}}/statuses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwNWUzN2I5Ny0xZDM4LTRkNDItYWQ3ZC1mZmQ4ZjgwZjAxZjMiLCJqdGkiOiI2NmRhZGI0Yy1iN2IxLTQ0NzItYmZkMC1iYzA5MDY5M2M1ODAiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwiZXhwIjoxNjgyMTg0NTI4LCJpc3MiOiJUYWJsZVRvcCBGcmllbmQiLCJhdWQiOiJUYWJsZVRvcCBGcmllbmQifQ.yr6nQnsWz721gdN-VOBSb3TpXlTztxPA71sSbPn1-RI

{
    "userId":"05e37b97-1d38-4d42-ad7d-ffd8f80f01f3",
    "name":"Vida",
    "description":"pontos de vida",
    "quantity":100
}