GET  {{host_https}}/{{api_v1_route}}/campaigns
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMjlkMTQ3NC05YWE1LTQwMTEtOWRiZC1jMGQ5OTlmMjEzYjIiLCJqdGkiOiJhN2U3MDA5YS00YzBiLTQ2MjAtYWEwNS1mZDBmYzVmODllM2IiLCJnaXZlbl9uYW1lIjoiQXRvcyIsImZhbWlseV9uYW1lIjoiUGVkcm8iLCJleHAiOjE2ODA0ODU3NzMsImlzcyI6IlRhYmxlVG9wIEZyaWVuZCIsImF1ZCI6IlRhYmxlVG9wIEZyaWVuZCJ9.YghtPU677W8JJHcEqHKOWs0a0kUayv5X8Lh4gDnvFik