POST {{host_https}}/{{api_v1_route}}/skills
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4ODBhNjFjOC03ZTQ4LTQzNjktYWQ4Yy0zMjk1NTIwZTczMmQiLCJqdGkiOiIxZGZiYmQ3OC1iNjhhLTRjMjQtOWQ3Zi02N2FlYzBlYTQ5NTMiLCJnaXZlbl9uYW1lIjoiQXRvcyIsImZhbWlseV9uYW1lIjoiUGVkcm8iLCJleHAiOjE2ODIxMjI2NjksImlzcyI6IlRhYmxlVG9wIEZyaWVuZCIsImF1ZCI6IlRhYmxlVG9wIEZyaWVuZCJ9.OF2TpWqJq8Fry_pKv3WPjCfB3JdJcONJhZXUgc8hmNE

{
    "userId":"880a61c8-7e48-4369-ad8c-3295520e732d",
    "statusId":"b9a0c029-6ed1-4b7f-b57c-0f5274bf15c5",
    "audioEffectId": "",
    "name":"fire ball",
    "description":"lauches a fire ball",
    "cost": 10
}