DELETE  {{host_https}}/{{api_v1_route}}/skills/af41c446-7d37-4e92-88ef-decdbacc35b2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwNWUzN2I5Ny0xZDM4LTRkNDItYWQ3ZC1mZmQ4ZjgwZjAxZjMiLCJqdGkiOiI3NzVhMzVmNy04NDNiLTQ0MTctOWE4YS1hZjcxNGYyNDVjODgiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwiZXhwIjoxNjgyMTg0OTQwLCJpc3MiOiJUYWJsZVRvcCBGcmllbmQiLCJhdWQiOiJUYWJsZVRvcCBGcmllbmQifQ.Wtauc3CgkqXA-bC-MtTTYRMnZgYTUcTmV6z2nA8AjJ4