GET {{host_https}}/{{api_v1_route}}/skills/list/880a61c8-7e48-4369-ad8c-3295520e732d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4ODBhNjFjOC03ZTQ4LTQzNjktYWQ4Yy0zMjk1NTIwZTczMmQiLCJqdGkiOiJkN2EwMTE2Yy02MmRiLTQ2YjAtYjllNS1hNDIyOWI5M2NmMzYiLCJnaXZlbl9uYW1lIjoiQXRvcyIsImZhbWlseV9uYW1lIjoiUGVkcm8iLCJleHAiOjE2ODIxMTQzMDUsImlzcyI6IlRhYmxlVG9wIEZyaWVuZCIsImF1ZCI6IlRhYmxlVG9wIEZyaWVuZCJ9.0VPwdXhogwvZfGbzqlL6DSEkXaVVM2lIHdiKCnJ_hwE