DELETE  {{host_https}}/{{api_v1_route}}/statuses/{Id}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4ODBhNjFjOC03ZTQ4LTQzNjktYWQ4Yy0zMjk1NTIwZTczMmQiLCJqdGkiOiI0OGRhZWQyMS1iNWVjLTQ4OWEtYTE4Mi04MTYzMzM2MWJjYzQiLCJnaXZlbl9uYW1lIjoiQXRvcyIsImZhbWlseV9uYW1lIjoiUGVkcm8iLCJleHAiOjE2ODIxMDA2OTcsImlzcyI6IlRhYmxlVG9wIEZyaWVuZCIsImF1ZCI6IlRhYmxlVG9wIEZyaWVuZCJ9.3eL8sbiJYHj4gBA8CpW9zHuu7VhoAi0nTnJ0WD58PYk