GET {{host_https}}/{{api_v1_route}}/statuses/b9a0c029-6ed1-4b7f-b57c-0f5274bf15c5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4ODBhNjFjOC03ZTQ4LTQzNjktYWQ4Yy0zMjk1NTIwZTczMmQiLCJqdGkiOiIxZGZiYmQ3OC1iNjhhLTRjMjQtOWQ3Zi02N2FlYzBlYTQ5NTMiLCJnaXZlbl9uYW1lIjoiQXRvcyIsImZhbWlseV9uYW1lIjoiUGVkcm8iLCJleHAiOjE2ODIxMjI2NjksImlzcyI6IlRhYmxlVG9wIEZyaWVuZCIsImF1ZCI6IlRhYmxlVG9wIEZyaWVuZCJ9.OF2TpWqJq8Fry_pKv3WPjCfB3JdJcONJhZXUgc8hmNE