POST {{host_https}}/{{api_v1_route}}/campaigns
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwNWUzN2I5Ny0xZDM4LTRkNDItYWQ3ZC1mZmQ4ZjgwZjAxZjMiLCJqdGkiOiI3NDgxMzVlZC03ZmU0LTRiMTItYTE4MC04YjU3NmY3ZmE2NGMiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwiZXhwIjoxNjgyMTgyMjM5LCJpc3MiOiJUYWJsZVRvcCBGcmllbmQiLCJhdWQiOiJUYWJsZVRvcCBGcmllbmQifQ.hiVPER6yLoXXwtijStzj4aCRGThPa-427iJWgPBp40o

{
   "name":"Out of the Abyss",
   "userId": "05e37b97-1d38-4d42-ad7d-ffd8f80f01f3",
   "description":"DEMOGOOOOORGON",
   "characterIds":[],
   "sessionIds":[]
}