POST {{host_https}}/{{api_v1_route}}/campaigns
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiYzA2YmJjMC0wZTdiLTQyZWUtOTliZS0yOThjNzE1OGFhYTEiLCJqdGkiOiI1NTIxYTcwZi0zYzRiLTRlNzUtOWQ2OS0zYWI0YzliNDgwM2YiLCJnaXZlbl9uYW1lIjoiZW1haWx0ZXN0ZTJAZ21haWwuY29tIiwiZmFtaWx5X25hbWUiOiJQZWRybzIiLCJleHAiOjE2ODE5MTEzOTgsImlzcyI6IlRhYmxlVG9wIEZyaWVuZCIsImF1ZCI6IlRhYmxlVG9wIEZyaWVuZCJ9.Mumyjq_ORUbh1xXnWC0E02aSRy537fSsG85wU7rFcDk

{
   "name":"Campaign 3",
   "userId": "bc06bbc0-0e7b-42ee-99be-298c7158aaa1",
   "description":"Campaign 3 desc",
   "characterIds":[],
   "sessionIds":[]
}