DELETE {{host_https}}/{{api_v1_route}}/campaigns/125c115a-f252-4cc6-923b-230ebe7b4d92
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZWJkOGJkNC1mNDQ1LTQ5YzYtOWUzOS04ZGE5NjMyODJkYzAiLCJqdGkiOiIxMjZjYTZiYy0zOTAyLTQ3NWEtOGFjMy1mZjU1MjdmZDk2OWUiLCJnaXZlbl9uYW1lIjoiQXRvcyIsImZhbWlseV9uYW1lIjoiUGVkcm8iLCJleHAiOjE2ODE3NDc0OTcsImlzcyI6IlRhYmxlVG9wIEZyaWVuZCIsImF1ZCI6IlRhYmxlVG9wIEZyaWVuZCJ9.kfaR3YD0I9OxYzdrasChtRn_aT_cnOZ0AjQGZ9ix16A