DELETE {{host_https}}/{{api_v1_route}}/campaigns/{CampaignId}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MWRhZmMwZC1kZTBmLTQ4MjItODRjYi00NzM3ZTViYjY4YWQiLCJqdGkiOiIyNDk5MzMxYS1hMWE3LTQ4ZTMtOGIzNi0wZGJkYWZlOTQ3OTEiLCJnaXZlbl9uYW1lIjoiQXRvcyIsImZhbWlseV9uYW1lIjoiUGVkcm8iLCJleHAiOjE2ODExMzYwNjksImlzcyI6IlRhYmxlVG9wIEZyaWVuZCIsImF1ZCI6IlRhYmxlVG9wIEZyaWVuZCJ9.ggLMGNITldy6EKtqotjvU-LjQvZRioO8yAXcrZZmnCk