DELETE {{host_https}}/{{api_v1_route}}/campaigns/cef91db6-e637-40a8-b4c9-914f037ea603
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZDllOWUzNy1mZjY2LTQ5OGYtYTRkNS01NjJhNmQwOWVmNjAiLCJqdGkiOiIyYWI5OGRkNS1kZWExLTRmYzYtOTE0NC01NTk2Njk5YzZkZTIiLCJnaXZlbl9uYW1lIjoiQXRvcyIsImZhbWlseV9uYW1lIjoiUGVkcm8iLCJleHAiOjE2ODE5MDQ2NTMsImlzcyI6IlRhYmxlVG9wIEZyaWVuZCIsImF1ZCI6IlRhYmxlVG9wIEZyaWVuZCJ9.70BrBG-eYjoai1lamqhDMarSgsx-96aUujbX2ebrsSE