GET {{host_https}}/{{api_v1_route}}/campaigns/13af0c29-0452-402f-b1dc-2103673bd18a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwNWUzN2I5Ny0xZDM4LTRkNDItYWQ3ZC1mZmQ4ZjgwZjAxZjMiLCJqdGkiOiIwZmJhZjM5Yi1mZTRlLTQyMGQtYmU2MC01YzQ5NDlkOGNiYjMiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwiZXhwIjoxNjgyMTgyNjA3LCJpc3MiOiJUYWJsZVRvcCBGcmllbmQiLCJhdWQiOiJUYWJsZVRvcCBGcmllbmQifQ.NJ6rcvu3QxnbY-YO2j_SEc3e3rD0DTkpgpGcCoZ8RIQ