GET {{host_https}}/{{api_v1_route}}/campaigns/all/{userId}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4NjBhYTQ1NC05Zjc5LTQzMGEtOWEzMC01MzRkY2IwZDE4YTciLCJqdGkiOiIzZDk4ZDA2OS04YzhjLTQ1ZjktYjMzNy0xZDdmY2Y5ZmNlYTUiLCJnaXZlbl9uYW1lIjoiZW1haWx0ZXN0ZUBnbWFpbC5jb20iLCJmYW1pbHlfbmFtZSI6IlBlZHJvIiwiZXhwIjoxNjgwNzIxMjQ3LCJpc3MiOiJUYWJsZVRvcCBGcmllbmQiLCJhdWQiOiJUYWJsZVRvcCBGcmllbmQifQ.6H0Pu2jHg6kxm448e8Jdyk9597U9HsgANAz6w8wDZjk
