GET {{host_https}}/{{api_v1_route}}/campaigns/704d6f50-95d8-43c3-89ac-1da8f37b4d3b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4NjBhYTQ1NC05Zjc5LTQzMGEtOWEzMC01MzRkY2IwZDE4YTciLCJqdGkiOiIzZDk4ZDA2OS04YzhjLTQ1ZjktYjMzNy0xZDdmY2Y5ZmNlYTUiLCJnaXZlbl9uYW1lIjoiZW1haWx0ZXN0ZUBnbWFpbC5jb20iLCJmYW1pbHlfbmFtZSI6IlBlZHJvIiwiZXhwIjoxNjgwNzIxMjQ3LCJpc3MiOiJUYWJsZVRvcCBGcmllbmQiLCJhdWQiOiJUYWJsZVRvcCBGcmllbmQifQ.6H0Pu2jHg6kxm448e8Jdyk9597U9HsgANAz6w8wDZjk