GET {{host_https}}/{{api_v1_route}}/campaigns/list/6d9e9e37-ff66-498f-a4d5-562a6d09ef60
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZDllOWUzNy1mZjY2LTQ5OGYtYTRkNS01NjJhNmQwOWVmNjAiLCJqdGkiOiJjZmM3NWYxYi03MTlkLTRjNzEtYWRiNC1lYWI4MDZlYWU1YjQiLCJnaXZlbl9uYW1lIjoiQXRvcyIsImZhbWlseV9uYW1lIjoiUGVkcm8iLCJleHAiOjE2ODE5MTE1NTksImlzcyI6IlRhYmxlVG9wIEZyaWVuZCIsImF1ZCI6IlRhYmxlVG9wIEZyaWVuZCJ9.rh2a9P0HexHohiMmMWg6BZwWEiDjGzifxSMyu2hM9lE
