GET {{host_https}}/{{api_v1_route}}/campaigns/list/880a61c8-7e48-4369-ad8c-3295520e732d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4ODBhNjFjOC03ZTQ4LTQzNjktYWQ4Yy0zMjk1NTIwZTczMmQiLCJqdGkiOiJhMTNmMDQwOS0yMzRmLTRiNGYtYjMwOC05ODYwMDMyN2VmMmIiLCJnaXZlbl9uYW1lIjoiQXRvcyIsImZhbWlseV9uYW1lIjoiUGVkcm8iLCJleHAiOjE2ODIxMTM3ODgsImlzcyI6IlRhYmxlVG9wIEZyaWVuZCIsImF1ZCI6IlRhYmxlVG9wIEZyaWVuZCJ9.pvv0KLEK64pEYRJ4HLoGwZLpR3TRWenNnBIn67fUQPk
