GET {{host_https}}/{{api_v1_route}}/campaigns/5b4989d2-a1da-44b2-9070-36b60f7155dd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1YjQ5ODlkMi1hMWRhLTQ0YjItOTA3MC0zNmI2MGY3MTU1ZGQiLCJqdGkiOiIyZjUzMWVjNS1iYmRiLTRhYzYtYjEzNC0yZTM2OTBiNWMyY2QiLCJnaXZlbl9uYW1lIjoiQXRvcyIsImZhbWlseV9uYW1lIjoiUGVkcm8iLCJleHAiOjE2ODEzMjcyNTcsImlzcyI6IlRhYmxlVG9wIEZyaWVuZCIsImF1ZCI6IlRhYmxlVG9wIEZyaWVuZCJ9._MT6YyfFVl_Sxl5jhsnwAXEoF9bH3Ew80e1rsjn_Eno