DELETE {{host_https}}/{{api_v1_route}}/characters/b4f95ae9-92a3-4623-9931-8067e6c8043c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNTMwOTczOC04OWU5LTRhZjYtYWM2Ni03M2M2NzU3N2Q2MjEiLCJqdGkiOiI0YmRhNDMyOS1hMDNjLTQ3NDYtODVkYy1hMjI2NTYwZWFkZjYiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwiZXhwIjoxNjgyMzUxMDg5LCJpc3MiOiJUYWJsZVRvcCBGcmllbmQiLCJhdWQiOiJUYWJsZVRvcCBGcmllbmQifQ.1AxdCbVfBEDHEr22xPKB0vQsyDoIMUKc3Vey62sLXZ4