DELETE {{host_https}}/{{api_v1_route}}/characters/fceabf25-e837-4dcf-baca-d49ad99820b5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNTMwOTczOC04OWU5LTRhZjYtYWM2Ni03M2M2NzU3N2Q2MjEiLCJqdGkiOiI0YWIwZTQyOS1jNWVhLTQ0MmQtOTJlMS1hYWQzZDA0ZDdiYjgiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwiZXhwIjoxNjgyMzU1MTMyLCJpc3MiOiJUYWJsZVRvcCBGcmllbmQiLCJhdWQiOiJUYWJsZVRvcCBGcmllbmQifQ.dUfOXZSNjQVmGyX_R_R_KQOOWrh3Z_nuWkZc5vmcaOU