POST {{host_https}}/{{api_v1_route}}/campaigns
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3NDgxOTU4Ny1iMWU5LTQxZjUtODk5Yy1mODEzYWE3Mjg3ZTgiLCJqdGkiOiJjMmFmODhiZC1mYTAzLTQwOGItYTQ2Zi0xMjA0OTI4MWM1NzgiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwiZXhwIjoxNjgzNDExODY0LCJpc3MiOiJUYWJsZVRvcCBGcmllbmQiLCJhdWQiOiJUYWJsZVRvcCBGcmllbmQifQ.MmyYuvaF_IyOyy0tCmf1QlBeTUNDqDz2azXQhddoh90

{
   "name":"Out of the Abyss",
   "userId": "74819587-b1e9-41f5-899c-f813aa7287e8",
   "description":"DEMOGOOOOORGON",
   "characterIds":[],
   "sessionIds":[]
}