POST {{host_https}}/{{api_v1_route}}/campaigns
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyNmFjNjU1Ny1hNzQ2LTRkNjktYWQ3MS0yYzJlNGY0YTQ4Y2QiLCJqdGkiOiIzNDg5MDgxMS01ZDdjLTQyNzItOWFkMS1jODBlYmM1NTliMGUiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwiZXhwIjoxNjkxMTY0OTIxLCJpc3MiOiJUYWJsZVRvcCBGcmllbmQiLCJhdWQiOiJUYWJsZVRvcCBGcmllbmQifQ.FTatt9XS-vq3AC9PQ4u_4rrqfLemaSqUt5uaxcYdSUU

{
   "name":"Out of the Abyss",
   "userId": "26ac6557-a746-4d69-ad71-2c2e4f4a48cd",
   "description":"DEMOGOOOOORGON",
   "characterIds":[],
   "sessionIds":[]
}