GET {{host_https}}/{{api_v1_route}}/campaigns/74819587-b1e9-41f5-899c-f813aa7287e8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3NDgxOTU4Ny1iMWU5LTQxZjUtODk5Yy1mODEzYWE3Mjg3ZTgiLCJqdGkiOiI5ZDU3ZWM1OC04NzJjLTRhNTYtODc4Zi02ZDQxN2I1ZDEwZTIiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwiZXhwIjoxNjgzNDEyMDA4LCJpc3MiOiJUYWJsZVRvcCBGcmllbmQiLCJhdWQiOiJUYWJsZVRvcCBGcmllbmQifQ.2PxLZepTqe2ggeW1j4kDuIb9OzPTpkqsdV4O6SIOCSU