POST {{host_https}}/{{api_v1_route}}/audio-effects
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNTMwOTczOC04OWU5LTRhZjYtYWM2Ni03M2M2NzU3N2Q2MjEiLCJqdGkiOiI1M2JjOGQ2My02M2Q1LTQ1NGEtYTAzYS1mMDZiMTZlNjE0YjgiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwiZXhwIjoxNjgyMzM4OTE1LCJpc3MiOiJUYWJsZVRvcCBGcmllbmQiLCJhdWQiOiJUYWJsZVRvcCBGcmllbmQifQ.8bJAZje_plbLqerzOfCaN3GgBwfFSLuzuK--0HslevY

{
    "userId":"b5309738-89e9-4af6-ac66-73c67577d621",
    "name":"fire ball audio",
    "description":"fire ball audio desc",
    "audioLink":"https://www.youtube.com/watch?v=FJGdoPmspiU",
    "audioClip":""
}